### ISSUE TITLE
Is it possible to use it on ubuntu? 

### ISSUE THREAD

**Issue by Doncode** [ohager/burst-autoplotter#37]
**node -v**
v4.2.6

**autoplot**
/usr/local/lib/node_modules/burst-autoplotter/bin/command/command.js:5
const { printUsage, printUnknownCommand, printUnknownOption } = require("./usage");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/burst-autoplotter/bin/autoplot.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by Doncode** [comment]
**node -v**
v8.11.1


**autoplot**
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/burst-autoplotter/bin/cache.js:35:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by ohager** [comment]
Unfortunately, the autoplotter doesn't work on other OSs than Windows. This is, because the underlying plotter (Blago's XPlotter) is exclusively for Windows. In fact, I'm not really satisfied with XPlotter as it's kind of unorganized and the SSE and AVX versions are different. I hope that with the launch of PoC2 (about 10th, June) new plotters may be launched, such that I could them instead of XPlotter. Sorry.
